name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        working-directory: ./app
        run: npm install

      - name: Expo Prebuild
        working-directory: ./app
        run: npx expo prebuild --platform android

      - name: Build APK
        working-directory: ./app/android
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Powerhub_24_7_APK
          path: app/android/app/build/outputs/apk/release/app-release.apk
